# texlib_bankreport.py
# ============================================================================
# TeXLib -- bank coverage report (D2) and bank preview (D3).
#
#   TeXLib: Bank Report   scan the bank + the document's \getproblem uses and
#                         report totals, topic/difficulty distribution, duplicate
#                         ids, unused problems, and dangling references.
#   TeXLib: Bank Preview  synthesize a \documentclass{bank} wrapper that
#                         \printbankcatalog's the resolved bank, open it, and
#                         build it (the catalog PDF) -- exercises bank.cls (B1).
#
# Own top-level file (hot-reloads alone). Pure helpers (bank_report / render_report
# / preview_wrapper / resolve_bank) are unit-tested headlessly.
# ============================================================================

import os
import re

import sublime
import sublime_plugin

try:
    from TeXLib import texlib_bank, texlib_topic
except ImportError:
    import texlib_bank
    import texlib_topic

# \getproblem{id} / \useproblem{id} / \reqproblem{id} -- a retrieval reference.
GET_RE = re.compile(r"\\(?:getproblem|useproblem|reqproblem)\{([^}]+)\}")


def referenced_ids(files):
    """Set of problem ids retrieved via \\getproblem/\\useproblem across files."""
    ids = set()
    for path in files:
        text = texlib_bank._read(path)
        if text is None:
            continue
        for m in GET_RE.finditer(text):
            ids.add(m.group(1).strip())
    return ids


def bank_report(problems, referenced):
    """Compute a coverage report dict from scanned `problems` and the set of
    `referenced` ids. Pure -- no Sublime, no disk."""
    ids = [p["id"] for p in problems]
    seen, dupes = set(), []
    for i in ids:
        if i in seen and i not in dupes:
            dupes.append(i)
        seen.add(i)
    defined = set(ids)
    topics = texlib_topic.topics_of(problems, "topic")
    diffs = texlib_topic.topics_of(problems, "difficulty")
    return {
        "total": len(problems),
        "distinct": len(defined),
        "duplicates": dupes,
        "topics": topics,
        "difficulties": diffs,
        "unused": sorted(defined - referenced),
        "dangling": sorted(referenced - defined),
    }


def render_report(rep, doc_name):
    """Render the report dict as a plain-text buffer."""
    L = ["TeXLib Bank Report — %s" % doc_name,
         "=" * 60, ""]
    L.append("Problems defined : %d  (%d distinct id%s)"
             % (rep["total"], rep["distinct"], "" if rep["distinct"] == 1 else "s"))
    L.append("Referenced       : %d used, %d unused"
             % (rep["distinct"] - len(rep["unused"]), len(rep["unused"])))
    L.append("")

    def section(title, rows):
        L.append(title)
        if rows:
            for lbl, _v in rows:
                L.append("    %s" % lbl)
        else:
            L.append("    (none)")
        L.append("")

    section("Topics:", rep["topics"])
    section("Difficulty:", rep["difficulties"])

    L.append("Duplicate ids (defined more than once):")
    L += ["    %s" % d for d in rep["duplicates"]] or ["    (none)"]
    L.append("")
    L.append("Unused (defined but never \\getproblem'd in this document):")
    L += ["    %s" % u for u in rep["unused"]] or ["    (none)"]
    L.append("")
    L.append("Dangling (\\getproblem'd but not defined in the bank):")
    L += ["    %s" % d for d in rep["dangling"]] or ["    (none)"]
    L.append("")
    return "\n".join(L)


def resolve_bank(doc_path, doc_text):
    """The bank file to preview: if the active file is itself a bare bank
    fragment (has \\begin{problem} and no \\documentclass), use it; else the
    document's first \\loadbank target or a sibling bank.tex."""
    if "\\begin{problem}" in doc_text and "\\documentclass" not in doc_text:
        return doc_path
    srcs = texlib_bank.problem_sources(doc_path, doc_text)
    for s in srcs[1:]:  # skip the doc itself (index 0)
        return s
    return None


def preview_wrapper(bank_path, wrapper_dir):
    r"""The \documentclass{bank} preview document text that catalogs `bank_path`,
    with a relative \loadbank so it resolves from the wrapper's own directory."""
    rel = os.path.relpath(bank_path, wrapper_dir).replace("\\", "/")
    if rel.lower().endswith(".tex"):
        rel = rel[:-4]
    return ("%% Auto-generated by TeXLib: Bank Preview. Safe to delete.\n"
            "%% !TeX program = lualatex\n"
            "\\documentclass{bank}\n"
            "\\begin{document}\n"
            "\\loadbank{%s}\n"
            "\\printbankcatalog\n"
            "\\end{document}\n" % rel)


class TexlibBankReportCommand(sublime_plugin.WindowCommand):
    """Open a coverage report for the active document's bank."""

    def run(self):
        view = self.window.active_view()
        doc_path, doc_text = texlib_bank._resolve_doc(view)
        if not doc_path:
            sublime.status_message("TeXLib: save the document first.")
            return
        files = texlib_bank.problem_sources(doc_path, doc_text)
        problems = texlib_bank.scan_problems(files)
        if not problems:
            sublime.status_message(
                "TeXLib: no bank problems found for this document.")
            return
        rep = bank_report(problems, referenced_ids(files))
        text = render_report(rep, os.path.basename(doc_path))
        out = self.window.new_file()
        out.set_name("TeXLib · Bank Report")
        out.set_scratch(True)
        out.run_command("append", {"characters": text})
        out.set_read_only(True)

    def is_enabled(self):
        return texlib_bank._is_tex(self.window.active_view())


class TexlibBankPreviewCommand(sublime_plugin.WindowCommand):
    """Build a \\printbankcatalog PDF of the resolved bank via \\documentclass{bank}."""

    def run(self):
        view = self.window.active_view()
        doc_path, doc_text = texlib_bank._resolve_doc(view)
        if not doc_path:
            sublime.status_message("TeXLib: save the document first.")
            return
        bank = resolve_bank(doc_path, doc_text)
        if not bank:
            sublime.status_message(
                "TeXLib: no bank found to preview (\\loadbank or a bank.tex).")
            return
        wrapper_dir = os.path.dirname(bank)
        wrapper = os.path.join(
            wrapper_dir,
            os.path.splitext(os.path.basename(bank))[0] + "-catalog.tex")
        try:
            with open(wrapper, "w", encoding="utf-8") as fh:
                fh.write(preview_wrapper(bank, wrapper_dir))
        except OSError as exc:
            sublime.error_message("TeXLib: could not write preview: %s" % exc)
            return
        new_view = self.window.open_file(wrapper)

        def build_when_ready():
            if new_view.is_loading():
                sublime.set_timeout(build_when_ready, 50)
                return
            self.window.focus_view(new_view)
            self.window.run_command("texlib_build", {"mode": "default"})

        sublime.set_timeout(build_when_ready, 50)

    def is_enabled(self):
        return texlib_bank._is_tex(self.window.active_view())


def plugin_loaded():
    print("TeXLib bank report/preview loaded.")
